[phases.setup]
cmds = ["npm install"]  # <-- Verander "npm ci" naar "npm install"

[phases.build]
cmds = ["echo 'No build needed'"]

[start]
cmd = "npx serve -s ."

[vars]
NIXPACKS_PATH = "/opt/nixpacks"
