export const modules = [
{ slug: "dashboard", title: "Dashboard" },
{ slug: "projecten", title: "Projecten" },
{ slug: "projecten-nieuw", title: "Nieuw project" },
{ slug: "calculator", title: "Calculaties" },
{ slug: "stabu-calculator", title: "STABU Calculator" },
{ slug: "fixed-price", title: "Fixed Price" },
{ slug: "bim", title: "BIM Architect" },
{ slug: "constructeurs", title: "Constructeurs" },
{ slug: "ew", title: "E en W" },
{ slug: "risicoanalyse", title: "Risico analyse" },
{ slug: "kopersportaal", title: "Kopersportaal" },
{ slug: "documenten", title: "Documenten" },
{ slug: "uploads", title: "Uploads" },
{ slug: "installatie", title: "Installatie" },
{ slug: "team", title: "Team" },
{ slug: "notificaties", title: "Notificaties" },
{ slug: "admin", title: "Instellingen" },

// uitbreiden tot 95+
{ slug: "investeringen", title: "Investeringen" },
{ slug: "cashflow", title: "Cashflow prognose" },
{ slug: "haalbaarheid", title: "Haalbaarheidsanalyse" },
{ slug: "inkoop", title: "Inkoop" },
{ slug: "leveranciers", title: "Leveranciers" },
{ slug: "contracten", title: "Contracten" },
{ slug: "planning", title: "Planning" },
{ slug: "kwaliteit", title: "Kwaliteitscontrole" },
{ slug: "veiligheid", title: "Veiligheid" },
{ slug: "bim-upload", title: "BIM Upload" },
{ slug: "bim-viewer", title: "BIM Viewer" },
{ slug: "calculatie-versies", title: "Calculatie versies" },
{ slug: "optimalisatie", title: "Optimalisatie" },
{ slug: "rapportages", title: "Rapportages" },
{ slug: "export", title: "Export" },
{ slug: "facturatie", title: "Facturatie" },
{ slug: "betalingen", title: "Betalingen" },
{ slug: "rollen", title: "Rollen en rechten" },
{ slug: "gebruikers", title: "Gebruikers" },
{ slug: "audit-log", title: "Audit log" }
]
