import { createClient } from "@supabase/supabase-js"
export const supabase = createClient("https://pmovazftwoxjopqkuuhp.supabase.co", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtb3ZhemZ0d294am9wcWt1dWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3NTA2NjIsImV4cCI6MjA4MDMyNjY2Mn0.8yZxX4mNhYUjhlnGVRlDHkdcU2241uKjXdwVCNvN89I")
